version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    shm_size: 128mb
    volumes:
      - ./../../.postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
  adminer:
    image: adminer
    restart: always
    ports:
      - 5431:8080
