openapi: 3.0.0
info:
  title: Enclave API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 1.0.0

servers:
  - url: https://api.myenclave.space
    description: Main (production) server

paths:
  /customer/{customerId}/booking:
    get:
      summary: List all the customer's current bookings
      description: Returns a list of all the customer's current bookings
      operationId: getCustomerBookings
      tags:
        - customer Booking
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string

  /customer/{customerId}/booking/{bookingId}:  
    patch:
      summary: Update unapproved booking
      description: Update given unapproved booking
      operationId: patchCustomerBooking
      tags:
        - customer Booking
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
    
    delete:
      summary: Cancel unapproved booking
      description: Cancel given unapproved booking
      operationId: deleteCustomerBooking
      tags:
        - customer Booking
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string

  /space/{spaceId}:
    post:
      summary: Creates a booking request for a space
      description: Book a space for a given customer
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string

tags:
  - name: customer Booking
    description: Every relationship between a customer and booking

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 4
        name:
          type: string
          example: Arthur Dent
      # Both properties are required
      required:  
        - id
        - name